on:
    push:
        branches:
            - 'e/*'
            - 'f/*'
            - 'b/*'
            - 't/*'

permissions:
    pull-requests: write

jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Create Pull Request
              run: |
                  gh pr create --title "${{ github.event.commits[0].message }}" --milestone 'next' || \
                  gh pr edit --add-assignee 'ragaeeb'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
